name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy_scan:
    name: Trivy Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          version: v0.57.1
          cache: true
          token: ${{ secrets.GITHUB_TOKEN }}
          path: $HOME/.local/bin

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: cache-trivy-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            cache-trivy-${{ runner.os }}-

      - name: Scan Docker Image with Trivy
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: react-app:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          vuln-type: os,library
          scanners: vuln,secret,misconfig
          scan-type: image
          scan-ref: .
          cache-dir: ~/.cache/trivy
          list-all-pkgs: false
          version: v0.57.1
          cache: true
          skip-setup-trivy: false

      - name: Handle Scan Failure
        if: failure()
        run: echo "Trivy scan found vulnerabilities. Please check logs and fix them!"
