name: Build and Deploy to AWS ECR & S3

on:
  push:
    branches:
      - main  # Trigger on main branch commits

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker Image
        run: |
          docker build -t my-react-app .
          docker tag my-react-app:latest ${{ secrets.AWS_ECR_REPO }}:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REPO }}:latest

      - name: Save Docker Image as .tar File
        run: |
          docker save -o my-react-app.tar ${{ secrets.AWS_ECR_REPO }}:latest

      - name: Upload Docker Image to S3
        run: |
          aws s3 cp my-react-app.tar s3://${{ secrets.S3_BUCKET_NAME }}/my-react-app.tar
