name: React App - Build & Scan with Trivy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual execution

jobs:
  build-and-scan:
    name: Build & Scan Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies & Build React App
        run: |
          npm install
          npm run build

      - name: Build Docker Image
        run: |
          docker build -t react-app:latest .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'react-app:latest'
          format: 'table'
          exit-code: '1'  # Fail workflow if vulnerabilities are found
          severity: 'CRITICAL,HIGH' # Only fail for HIGH & CRITICAL issues
          ignore-unfixed: true  # Ignore vulnerabilities without fixes
          vuln-type: 'os,library'  # Scan both OS & app dependencies
          scanners: 'vuln,secret,config'  # Scan for vulnerabilities, secrets, misconfigurations
